/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."

#endif
//Global Variable
unsigned char ch ;

#include "Stm32_f103c6_Drivers_Gpio.h"
#include "Stm32f103x6.h"
#include "KEY_PAD.h"
#include "LCD.h"
#include "Stm32_f103c6_Drivers_EXTI.h"
#include "Stm32_f103c6_Drivers_USART.h"
#include "Stm32_f103c6_Drivers_RCC.h"


void clock_init(){
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();

}


int main(void)
{
	USART_Config USARTCFG ;

	clock_init();

	USARTCFG.BaudRate = USART_BaudRate_115200;
	USARTCFG.FlowControl = USART_FlowControl_NONE;
	USARTCFG.IRQ_Enable = USART_NONE;
	USARTCFG.P_CallBack_Fun = NULL ;
	USARTCFG.Parity = USART_Parity_None;
	USARTCFG.Payload_length = USART_DataLength8B;
	USARTCFG.StopBits = USART_StopBits_1;
	USARTCFG.USART_Mode = USART_TX_RX;
	USART_init(USART1 , &USARTCFG);
	USART_SetPins(USART1);


	while (1)
	{
		USART_Send(USART1  , &ch , Enable );
		USART_Recieve(USART1, &ch , Enable );

	}


}


