/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <Stm32_f103C6_Drivers.h>
#include <Stm32f103x6.h>
#include <alarm.h>
#include <Pressure_Sensor.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//Learn-in-depth
//Hady-Samir
//Mastering_Embedded System online diploma


int main(void)
{
	RCC_GPIOA_ENABLE() ;

	Pressure_Sensor_init();
	alarm_init();

	while(1)
	{
		if (Pressure_Sensor_Read() == High_Pressure)
		start_alarm();

		Stop_alarm();
	}
}
