/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//Learn-in-depth
//Hady-Samir
//Mastering_Embedded System online diploma

typedef volatile unsigned int vuint32_t ;


// GPIO
#define GPIOA_BASE  0x40010800
#define GPIOA_CRH   *(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR   *(vuint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL   *(vuint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_IDR   *(vuint32_t *)(GPIOA_BASE + 0x08h)

// RCC
#define RCC_BASE    0x40021000
#define RCC_APB2ENR *(vuint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR    *(vuint32_t *)(RCC_BASE + 0x04)
#define RCC_CR      *(vuint32_t *)(RCC_BASE + 0x00)

// EXTI
#define EXTI_BASE   0x40010400
#define EXTI_IMR    *(vuint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR   *(vuint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR     *(vuint32_t *)(EXTI_BASE + 0x14)
#define NVIC_ISER0  *(vuint32_t *)(0xE000E100)

// AFIO
#define AFIO_BASE   0x4001000
#define AFIO_EXTICR1 *(vuint32_t *)(AFIO_BASE + 0x08)

void Clock_init(void)
{

	RCC_APB2ENR |= (1<<2);          // Enable Clock for GPIOA
	RCC_APB2ENR |= (1<<0);          // Alternate function IO clock enable
}

void GPIO_init(void)
{
	//pin13 portA output (General purpose output push-pull, max speed 2 MHz)
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	//01: Floating input (reset state), pin0 is floating because this pin will lined with button
	GPIOA_CRL &=0xFFFFFFF0;
	GPIOA_CRL |=(1<<3);
	// External interrupt configuration register for PA0
	AFIO_EXTICR1 = 0;

}

void EXTI_init(void)
{
	EXTI_IMR |= (1<<0); // Interrupt mask register enable for EXTI0
	EXTI_RTSR |= (1<<0); //  Rising trigger enabled for EXTI0

	//from Vector table>>>EXTI0>>>Position 6 at hardware
	NVIC_ISER0 |= (1<<6); // Enable NVIC IRQ 6 (EXTI0)
}

enum userlevel
{
	privileged,
	unprivileged,

};
void SWITCH_USER_LEVEL(enum userlevel level)
{
	switch(level)
	{
	case privileged :
		__asm("mrs r3, CONTROL \n\t"
				"lsr r3, r3 , #0x1 \n\t"
				"lsl r3, r3 , #0x1 \n\t");
	break;

	case unprivileged :
			__asm("mrs r3, CONTROL \n\t"
				  "orr r3, r3 , #0x1 \n\t"
				  "msr CONTROL, r3 \n\t");
		break;


	}
}

int main(void)
{
	Clock_init();
	GPIO_init();
	EXTI_init();
	SWITCH_USER_LEVEL(privileged);
	SWITCH_USER_LEVEL(unprivileged);

	while(1);
}

void EXTI0_IRQHandler()
{

	// Toggle LED on pin 13
	GPIOA_ODR ^= (1<<13) ;

	// Clear pending status of EXTI0
	EXTI_PR |= (1<<0);
}
