/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//Learn-in-depth
//Hady-Samir
//Mastering_Embedded System online diploma

typedef volatile unsigned int vuint32_t ;


// GPIOA
#define GPIOA_BASE  0x40010800
#define GPIOA_CRH   *(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR   *(vuint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA_CRL   *(vuint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_IDR   *(vuint32_t *)(GPIOA_BASE + 0x08)
// GPIOB
#define GPIOB_BASE  0x40010C00
#define GPIOB_CRH   *(vuint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_ODR   *(vuint32_t *)(GPIOB_BASE + 0x0C)
#define GPIOB_CRL   *(vuint32_t *)(GPIOB_BASE + 0x00)
#define GPIOB_IDR   *(vuint32_t *)(GPIOB_BASE + 0x08h)

// RCC
#define RCC_BASE    0x40021000
#define RCC_APB2ENR *(vuint32_t *)(RCC_BASE + 0x18)
#define RCC_CFGR    *(vuint32_t *)(RCC_BASE + 0x04)
#define RCC_CR      *(vuint32_t *)(RCC_BASE + 0x00)

// EXTI
#define EXTI_BASE   0x40010400
#define EXTI_IMR    *(vuint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR   *(vuint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR     *(vuint32_t *)(EXTI_BASE + 0x14)
#define NVIC_ISER0  *(vuint32_t *)(0xE000E100)

// AFIO
#define AFIO_BASE   0x4001000
#define AFIO_EXTICR1 *(vuint32_t *)(AFIO_BASE + 0x08)

void Clock_init(void)
{

	RCC_APB2ENR |= (1<<2);          // Enable Clock for GPIOA
	RCC_APB2ENR |= (1<<3);          // Enable Clock for GPIOB

}

void GPIO_init(void)
{
	//GPIOA PA1 Floating input (reset state)
	GPIOA_CRL &= (0XFFFFFF0F);
	GPIOA_CRL |= (1<<6);


	//GPIOA PA13 Floating input (reset state)
	GPIOA_CRH &= (0XFFFFFF0F);
	GPIOA_CRH |= (0b01<<22);


	//GPIOA PB1 General purpose output push-pull max speed 10 MHz
	GPIOB_CRL &= (0XFFFFFF0F);
	GPIOB_CRL |= (0b0001<<4);//max speed 10 MHz


	//GPIOA PB13 General purpose output push-pull max speed 10 MHz
	GPIOB_CRH &= (0XFF0FFFFF);
	GPIOB_CRH |= (0b01<<20);//max speed 10 MHz
	GPIOB_CRH |= (0b00<<22);//General purpose output push-pull


}

int main(void)
{
    int delay = 0;
	Clock_init();
	GPIO_init();

	while(1)
	{
		if(((GPIOA_IDR & (1<<1))>>1) == 0)//press
		{
			GPIOB_ODR ^=(1<<1);
			while(((GPIOA_IDR & (1<<1))>>1) == 0);//single press

		}
		if(((GPIOA_IDR & (1<<13))>>13) == 1)//press
				{
					GPIOB_ODR ^=(1<<13);//Multi pressing
		            for (delay = 0 ; delay < 10000 ; delay ++);
				}
	}
}

