/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."

#endif
//Global Variable
unsigned int IRQ_Flag =0;


#include "Stm32_f103c6_Drivers_Gpio.h"
#include "Stm32f103x6.h"
#include "KEY_PAD.h"
#include "LCD.h"
#include "Stm32_f103c6_Drivers_EXTI.h"


//#include "KEY_PAD.h"
void clock_Init(){
	RCC_GPIOA_CLK_EN();//For LCD
	RCC_GPIOB_CLK_EN();//Floating Input
	RCC_AFIO_CLK_EN();//AFIO

}
void GPIOB_INIT(){


}
my_wait(int a){
	unsigned int i,j;
	for(i=0;i<a;i++)
		for(j=0;j<255;j++);
}
void EXTI9_CALLBACK(void){
	IRQ_Flag=1;
	LCD_Send_String("IRQ EXTI9 PORTB");
	LCD_Send_A_Command(LCD_BEGIN_AT_SECOND_RAW);
	LCD_Send_String("IRQ DONE _|-");
	my_wait(1000);
}
int main(void)
{
	//Enable clock
	clock_Init();
	//Enable LCD
	LCD_init();
	//Clear LCD
	LCD_clear_screen();
	//EXTI Input == EXTI9>>Port B Pin 9
	EXTI_Pinconfig_t CFG;
	CFG.EXTI_PIN=EXTI9PB9;
	//Raising
	CFG.Trigger_Case=EXTI_TRIGGER_RAISING;
	//Call >> CallBack == EXTI9_CALLBACK
	CFG.P_IRQ_CALLBACK=EXTI9_CALLBACK;
	//Enable IRQ Mask
	CFG.IRQ_EN=EXTI_IRQ_ENABLE;

	//Init CFG
	MCAL_EXTI_GPIO_Init(&CFG);

	IRQ_Flag=1;
	while(1){
		if(IRQ_Flag){
			//Clear LCD
			LCD_clear_screen();
			IRQ_Flag=1;
		}
	}
}
